version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: confess-node
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true
    command: npm run dev
